/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.flink.streaming.api.windowing.time;

import org.apache.flink.annotation.Public;

import java.util.concurrent.TimeUnit;

import static org.apache.flink.util.Preconditions.checkNotNull;

/**
 * The definition of a time interval for windowing. The time characteristic referred
 * to is the default time characteristic set on the execution environment.
 */
/**
 * 定义了窗口中的时间间隔
 * 引用的时间特征是在执行环境中设置的默认时间特征
 */
@Public
public final class Time {

	/** The time unit for this policy's time interval. */
	// 时间单位
	private final TimeUnit unit;

	/** The size of the windows generated by this policy. */
	// 时间量级
	private final long size;

	/** Instantiation only via factory method. */
	private Time(long size, TimeUnit unit) {
		this.unit = checkNotNull(unit, "time unit may not be null");
		this.size = size;
	}

	// ------------------------------------------------------------------------
	//  Properties
	// ------------------------------------------------------------------------

	/**
	 * Gets the time unit for this policy's time interval.
	 * @return The time unit for this policy's time interval.
	 */
	/**
	 * 获取时间单位
	 */
	public TimeUnit getUnit() {
		return unit;
	}

	/**
	 * Gets the length of this policy's time interval.
	 * @return The length of this policy's time interval.
	 */
	/**
	 * 获取时间间隔
	 */
	public long getSize() {
		return size;
	}

	/**
	 * Converts the time interval to milliseconds.
	 * @return The time interval in milliseconds.
	 */
	/**
	 * 将窗口长度转为毫秒表示
	 */
	public long toMilliseconds() {
		return unit.toMillis(size);
	}

	// ------------------------------------------------------------------------
	//  Factory
	// ------------------------------------------------------------------------

	/**
	 * Creates a new {@link Time} of the given duration and {@link TimeUnit}.
	 *
	 * <p>The {@code Time} refers to the time characteristic that is set on the dataflow via
	 * {@link org.apache.flink.streaming.api.environment.StreamExecutionEnvironment#setStreamTimeCharacteristic(org.apache.flink.streaming.api.TimeCharacteristic)}.
	 *
	 * @param size The duration of time.
	 * @param unit The unit of time of the duration, for example {@code TimeUnit.SECONDS}.
	 * @return The time policy.
	 */
	/**
	 * 工厂函数，根据不同的 TimeUnit 创建 Time 实例
	 */
	public static Time of(long size, TimeUnit unit) {
		return new Time(size, unit);
	}

	/**
	 * Creates a new {@link Time} that represents the given number of milliseconds.
	 */
	/**
	 * 快捷创建 TimeUnit 为 MILLISECONDS 的 Time 实例
	 */
	public static Time milliseconds(long milliseconds) {
		return of(milliseconds, TimeUnit.MILLISECONDS);
	}

	/**
	 * Creates a new {@link Time} that represents the given number of seconds.
	 */
	/**
	 * 快捷创建 TimeUnit 为 SECONDS 的 Time 实例
	 */
	public static Time seconds(long seconds) {
		return of(seconds, TimeUnit.SECONDS);
	}

	/**
	 * Creates a new {@link Time} that represents the given number of minutes.
	 */
	/**
	 * 快捷创建 TimeUnit 为 MINUTES 的 Time 实例
	 */
	public static Time minutes(long minutes) {
		return of(minutes, TimeUnit.MINUTES);
	}

	/**
	 * Creates a new {@link Time} that represents the given number of hours.
	 */
	/**
	 * 快捷创建 TimeUnit 为 HOURS 的 Time 实例
	 */
	public static Time hours(long hours) {
		return of(hours, TimeUnit.HOURS);
	}

	/**
	 * Creates a new {@link Time} that represents the given number of days.
	 */
	/**
	 * 快捷创建 TimeUnit 为 DAYS 的 Time 实例
	 */
	public static Time days(long days) {
		return of(days, TimeUnit.DAYS);
	}
}
